### ISSUE TITLE
organization type schema

### ISSUE THREAD

**Issue by topty** [nitpum/KMUTT-CPE231-OnlineBanking-1#4]
https://github.com/nitpum/KMUTT-CPE231-OnlineBanking-1/blob/222fc857c4669908275b6a59f90f8afd219de034/backend/models/organization/schema.js#L5-L5

![image](https://user-images.githubusercontent.com/1586856/58529678-006bf300-8206-11e9-8696-002091de8f3a.png)

**Comment by nitpum** [comment]
![image](https://user-images.githubusercontent.com/2589606/58529735-31e4be80-8206-11e9-95cf-6d4dfe2a076a.png)
Organization has Type 
ServiceReference and ServiceType is difference thing from Organization
